### ISSUE TITLE
[Android] Tapping "Refresh" button on feedback screen and then "Back" button causes application to force close

### ISSUE THREAD

**Issue by drptbl** [hicsail/ionic-hockeyapp#5]
Android 6.0.1
Samsung Galaxy S6

Reproduction steps:
1. Tap on button which calls `this.hockeyapp.feedback();`
2. Create a new issue
3. Tap on "Refresh" button
4. Tap on "Back" button to go back to app out of "Feedback" screen => causes application to close instead going back to app

Logcat:
```
05-12 15:37:08.828  3476  3575 W WindowAnimator: Failed to dispatch window animation state change.
05-12 15:37:08.828  3476  3575 W WindowAnimator: android.os.DeadObjectException
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:607)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:535)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:1203)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at com.android.server.wm.WindowAnimator.access$000(WindowAnimator.java:95)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:182)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:695)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:628)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:739)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.Looper.loop(Looper.java:158)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
05-12 15:37:08.828  3476  3575 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by gregfrasco** [comment]
Thank you for bringing this to my attentions. I have updated the [example ionic application](https://github.com/hicsail/ionic-hockeyapp/tree/master/example) to handle this. I will not add the fix to this package because it the author of the application wants to change the functional they can, I will provide more documentation of this in the near future. Please refer to the [app.component.ts](https://github.com/hicsail/ionic-hockeyapp/blob/master/example/src/app/app.component.ts) file in the example for the solution.

**Comment by drptbl** [comment]
@gregfrasco Thank you!
